action: update code

diff --git a/disable_workflow/Build-OpenWrt_Multi-Platform(V3).yml b/disable_workflow/Build-OpenWrt_Multi-Platform(V3).yml
--- a/disable_workflow/Build-OpenWrt_Multi-Platform(V3).yml
+++ b/disable_workflow/Build-OpenWrt_Multi-Platform(V3).yml
@@ -57,7 +57,6 @@ jobs:
         id: gen_release_tag
         run: |
           echo "release_tag=multi-platform_$(date +"%Y.%m.%d_%H.%M.%S")" >> $GITHUB_OUTPUT
-
       - name: Checkout
         uses: actions/checkout@v4
         with:
@@ -67,7 +66,6 @@ jobs:
         id: read-platforms
         run: |
           bash $PLATFORMS_SH
-
   
   job_source_init:
     needs: job_init
@@ -78,6 +76,7 @@ jobs:
       matrix:
         include: ${{ fromJson(needs.job_init.outputs.platforms_source) }}
     steps:
+
       - name: Init System
         id: init
         run: |
@@ -89,7 +88,6 @@ jobs:
           sudo chown $USER:$GROUPS /workdir/output
           ln -sf /workdir/output $GITHUB_WORKSPACE/output
           df -hT
-
       - name: Checkout
         uses: actions/checkout@v4
         with:
@@ -100,14 +98,12 @@ jobs:
         run: |
           git clone ${{ matrix.value.REPO_URL }} openwrt
           ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
-
       - name: Load Custom Feeds
         run: |
           [ -e $FEEDS_CONF ] && cp -r ${{ matrix.value.FEEDS_CONF }} openwrt/feeds.conf.default
           chmod +x ${{ matrix.value.DIY_P1_SH }}
           cd openwrt
           $GITHUB_WORKSPACE/${{ matrix.value.DIY_P1_SH }}
-
       - name: Update Feeds
         run: cd openwrt && ./scripts/feeds update -a
 
@@ -119,7 +115,6 @@ jobs:
           git fetch origin
           git reset --hard origin/${{ github.ref_name }}
           git checkout -b temp-${{ matrix.source_code_platform }}
-
       - name: Make Defconfig Custom Configuration
         run: |
           chmod +x ${{ matrix.value.DIY_P2_SH }}
@@ -127,37 +122,30 @@ jobs:
           cd openwrt
           $GITHUB_WORKSPACE/${{ matrix.value.DIY_P2_SH }}
           $GITHUB_WORKSPACE/$MAKE_DEFCONFIG_SH "${{ matrix.source_code_platform }}" "${{ matrix.value.CONFIGS }}"
-
       - name: Merge and push changes with "theirs" strategy
         run: |
           git checkout temp-${{ matrix.source_code_platform }}
           git add .
-
           if ! git diff --cached --quiet; then
             git config user.name "smallprogram"
             git config user.email "smallprogram@foxmail.com"
             git commit -m "Auto update for ${{ matrix.source_code_platform }} configuration"
-
             git checkout ${{ github.ref_name }}
             git fetch origin
             git reset --hard origin/${{ github.ref_name }}
-
             git checkout temp-${{ matrix.source_code_platform }}
             git merge origin/${{ github.ref_name }} --no-ff --strategy-option theirs --no-edit || {
               echo "Merge conflict in temp branch, please resolve manually."
               exit 100
             }
-
             git checkout ${{ github.ref_name }} 
             git merge temp-${{ matrix.source_code_platform }} --strategy-option theirs --no-edit
             git push origin ${{ github.ref_name }} --force
             git branch -d temp-${{ matrix.source_code_platform }} || echo "Local temp-${{ matrix.source_code_platform }} not found"
             git push origin --delete temp-${{ matrix.source_code_platform }} || echo "Remote temp-${{ matrix.source_code_platform }} not found"
-
           else
             echo "No changes to commit."
           fi
-
       - name: Generate Source Packages
         working-directory: /workdir
         id: generate_image
@@ -166,13 +154,11 @@ jobs:
           du -hs openwrt/
           echo
           tar -czf output/output.tar.gz openwrt/
-
           echo "source code size:"
           cd output
           ls -lh output.tar.gz
           echo "SOURCE_PATH=$PWD" >> $GITHUB_ENV
           echo "status=success" >> $GITHUB_OUTPUT
-
       - name: Upload Source To Artifact
         uses: actions/upload-artifact@v4
         if: steps.generate_image.outputs.status == 'success'
@@ -214,76 +200,68 @@ jobs:
     name: Generate-Release-Tag-And-Git-Log
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
+    - name: Checkout
+      uses: actions/checkout@v4
+      with:
+        fetch-depth: 0
 
-      - name: Pull the latest changes and Create temporary branch
-        run: |
+    - name: Pull the latest changes and Create temporary branch
+      run: |
+        git fetch origin
+        git reset --hard origin/${{ github.ref_name }}
+        git checkout -b temp-tag-gitlog
+    - name: Download Git Log From Artifacts
+      id : download_gitlog
+      uses: actions/download-artifact@v4
+      with:
+        pattern: git_log_*
+        merge-multiple: true
+
+    - name: Download Release Tag From Artifacts
+      id : download_releasetag
+      uses: actions/download-artifact@v4
+      with:
+        pattern: release_*
+        merge-multiple: true
+
+    - name: Generate Release Tag
+      id: tag
+      run: |
+        chmod +x $UPDATE_GIT_LOG_SH
+        $GITHUB_WORKSPACE/$UPDATE_GIT_LOG_SH "${{ needs.job_init.outputs.output_release_tag }}"
+    - name: Upload Tags To Artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: release_tag
+        path: release.txt
+        retention-days: 5
+
+    - name: Merge and push changes with "theirs" strategy
+      run: |
+        
+        git checkout temp-tag-gitlog
+        rm -rf release.txt
+        git add .
+        if ! git diff --cached --quiet; then
+          git config user.name "smallprogram"
+          git config user.email "smallprogram@foxmail.com"
+          git commit -m "Auto update git log"
+          git checkout ${{ github.ref_name }}
           git fetch origin
           git reset --hard origin/${{ github.ref_name }}
-          git checkout -b temp-tag-gitlog
-
-      - name: Download Git Log From Artifacts
-        id : download_gitlog
-        uses: actions/download-artifact@v4
-        with:
-          pattern: git_log_*
-          merge-multiple: true
-
-      - name: Download Release Tag From Artifacts
-        id : download_releasetag
-        uses: actions/download-artifact@v4
-        with:
-          pattern: release_*
-          merge-multiple: true
-
-      - name: Generate Release Tag
-        id: tag
-        run: |
-          chmod +x $UPDATE_GIT_LOG_SH
-          $GITHUB_WORKSPACE/$UPDATE_GIT_LOG_SH "${{ needs.job_init.outputs.output_release_tag }}"
-
-      - name: Upload Tags To Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: release_tag
-          path: release.txt
-          retention-days: 5
-
-      - name: Merge and push changes with "theirs" strategy
-        run: |
-          
           git checkout temp-tag-gitlog
-          rm -rf release.txt
-          git add .
-
-          if ! git diff --cached --quiet; then
-            git config user.name "smallprogram"
-            git config user.email "smallprogram@foxmail.com"
-            git commit -m "Auto update git log"
-
-            git checkout ${{ github.ref_name }}
-            git fetch origin
-            git reset --hard origin/${{ github.ref_name }}
-
-            git checkout temp-tag-gitlog
-            git merge origin/${{ github.ref_name }} --no-ff --strategy-option theirs --no-edit || {
-              echo "Merge conflict in temp branch, please resolve manually."
-              exit 100
-            }
-
-            git checkout ${{ github.ref_name }} 
-            git merge temp-tag-gitlog --strategy-option theirs --no-edit
-            git push origin ${{ github.ref_name }} --force
-            git branch -d temp-tag-gitlog || echo "Local temp-tag-gitlog not found"
-            git push origin --delete temp-tag-gitlog || echo "Remote temp-tag-gitlog not found"
-
-          else
-            echo "No changes to commit."
-          fi
-
+          git merge origin/${{ github.ref_name }} --no-ff --strategy-option theirs --no-edit || {
+            echo "Merge conflict in temp branch, please resolve manually."
+            exit 100
+          }
+          git checkout ${{ github.ref_name }} 
+          git merge temp-tag-gitlog --strategy-option theirs --no-edit
+          git push origin ${{ github.ref_name }} --force
+          git branch -d temp-tag-gitlog || echo "Local temp-tag-gitlog not found"
+          git push origin --delete temp-tag-gitlog || echo "Remote temp-tag-gitlog not found"
+        else
+          echo "No changes to commit."
+        fi
   job_build_toolchain:
     needs: [job_init, job_source_init, job_generate_release_tag]
     runs-on: ${{ matrix.value.OS }}
@@ -330,7 +308,6 @@ jobs:
           # sudo -E apt-get -qq clean
           sudo timedatectl set-timezone "$TZ"
           df -hT
-
       - name: Initialization Directory
         working-directory: /workdir
         id: init_directory
@@ -339,10 +316,8 @@ jobs:
           sudo mkdir -p download
           sudo chown $USER:$GROUPS /workdir/openwrt
           sudo chown $USER:$GROUPS /workdir/download
-
           ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
           ln -sf /workdir/download $GITHUB_WORKSPACE/download
-
       - name: Download Source From Artifacts
         id : download
         uses: actions/download-artifact@v4
@@ -361,7 +336,6 @@ jobs:
           echo "TAG_PATH=$PWD" >> $GITHUB_ENV
           cd ..
           sudo chown -R $USER:$GROUPS /workdir/openwrt
-
       - name: Load Configuration
         run: |
           # chmod +x $COPY_BACKGROUNDFILES_SH
@@ -369,7 +343,6 @@ jobs:
           cd openwrt
           make defconfig
           # $GITHUB_WORKSPACE/$COPY_BACKGROUNDFILES_SH "" "${{ matrix.platform }}"
-
       - name: Download Package
         id: package
         run: |
@@ -430,21 +403,17 @@ jobs:
             exit $is_complie_error
           fi
           df -hT
-
       - name: Generate Source Packages
         working-directory: /workdir
         id: generate_image
         run: |
           echo "source toolchain folder size:"
           du -hs openwrt/
-
           sudo mkdir -p output
           sudo chown $USER:$GROUPS /workdir/output
           ln -sf /workdir/output $GITHUB_WORKSPACE/output
-
           echo
           tar -czf output/output_toolchain.tar.gz openwrt/
-
           echo "source toolchain file size:"
           cd output
           ls -lh output_toolchain.tar.gz
@@ -507,7 +476,6 @@ jobs:
           # sudo -E apt-get -qq clean
           sudo timedatectl set-timezone "$TZ"
           df -hT
-
       - name: Initialization Directory
         working-directory: /workdir
         id: init_directory
@@ -516,15 +484,19 @@ jobs:
           sudo mkdir -p download
           sudo chown $USER:$GROUPS /workdir/openwrt
           sudo chown $USER:$GROUPS /workdir/download
-
           ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
           ln -sf /workdir/download $GITHUB_WORKSPACE/download
-
       - name: Download Source From Artifacts
         id : download
         uses: actions/download-artifact@v4
         with:
           name: Source_${{ matrix.source_code_platform }}_${{ matrix.platform }}
+          path: download
+
+      - name: Download Tags
+        uses: actions/download-artifact@v4
+        with:
+          name: release_tag
           path: download
 
       - name: File Extraction
@@ -570,10 +542,7 @@ jobs:
                 is_complie_error=${PIPESTATUS[0]}
             fi
           fi
-
-
           
-
           echo "complie result： $is_complie_error"
           if [ "$is_complie_error" -eq 0 ]; then
             echo "status=success" >> $GITHUB_OUTPUT
@@ -581,9 +550,7 @@ jobs:
             echo "status=failure" >> $GITHUB_OUTPUT
             exit $is_complie_error
           fi
-
           df -hT
-
       - name: Check Space Usage
         if: (!cancelled())
         run: df -hT
@@ -611,7 +578,6 @@ jobs:
           # if [[ "${{ matrix.source_code_platform }}" == "lede" ]]; then
           #     exit 200
           # fi
-
           
           cd $GITHUB_WORKSPACE/openwrt/bin/targets/*/*
           mkdir -p feeds_packages
@@ -622,11 +588,8 @@ jobs:
           
           # zip -r buildinfo_${{ matrix.source_code_platform }}_${{ matrix.platform }}.zip feeds_packages packages sha256sums version.buildinfo config.buildinfo feeds.buildinfo
           # rm -rf packages feeds_packages sha256sums version.buildinfo config.buildinfo feeds.buildinfo
-
           find . ! -name '*-*-*' -exec zip buildinfo_${{ matrix.source_code_platform }}_${{ matrix.platform }}.zip {} +
           find . -mindepth 1 ! \( -name '*-*-*' -o -name '*.zip' \) -exec rm -rf {} +
-
-
           if [[ "${{ matrix.source_code_platform }}" == "lede" ]]; then
               for file in openwrt-*; do
                   if [[ -f "$file" ]]; then
@@ -634,12 +597,9 @@ jobs:
                   fi
               done
           fi
-
           ls
-
           echo "FIRMWARE=$firmware_path" >> $GITHUB_ENV
           echo "status=success" >> $GITHUB_OUTPUT
-
       - name: Upload Firmware Directory To Artifact
         uses: actions/upload-artifact@v4
         if: steps.organize.outputs.status == 'success' && env.UPLOAD_ARTIFACT == 'true' && !cancelled()
@@ -647,130 +607,63 @@ jobs:
           name: ${{ matrix.source_code_platform }}_${{ matrix.platform }}_firmware
           path: ${{ env.FIRMWARE }}
 
-
-  job_upload_release:
-    needs: [job_init, job_source_init, job_generate_release_tag, job_build_toolchain, job_build]
-    runs-on: ${{ matrix.value.OS }}
-    if: ${{ always() }}
-    strategy:
-      fail-fast: false
-      matrix:
-        include: ${{ fromJson(needs.job_init.outputs.platforms) }}
-    name: UploadRelease-${{ matrix.source_code_platform }}-${{ matrix.platform }}
-
-    steps:
-      - name: Initialization Environment
-        run: |
-          sudo timedatectl set-timezone "$TZ"
-          df -hT
-          sudo mkdir -p release_download
-          sudo mkdir -p release_tag_download
-
-
-      - name: Download Release From Artifacts
-        id : download
-        uses: actions/download-artifact@v4
-        with:
-          name: ${{ matrix.source_code_platform }}_${{ matrix.platform }}_firmware
-          path: release_download
-
-      - name: Download Tags
-        uses: actions/download-artifact@v4
-        with:
-          name: release_tag
-          path: release_tag_download
-
-      - name: File Extraction
-        working-directory: /workdir
-        run: |
-          echo "release files:"
-          cd release_download
-          ls
-          echo "RELEASE_PATH=$PWD" >> $GITHUB_ENV
-          cd ..
-          cd release_tag_download
-          echo "RELEASE_TAG_PATH=$PWD" >> $GITHUB_ENV
-      
-      - name: SSH connection to Actions
-        uses: mxschmitt/action-tmate@v3.16
-        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
-
-
       - name: Upload Firmware To Release
         uses: softprops/action-gh-release@v2.0.8
+        if: steps.organize.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ needs.job_init.outputs.output_release_tag }}
-          body_path: ${{ env.RELEASE_TAG_PATH }}/release.txt
-          files: ${{ env.RELEASE_PATH }}/*
-        
-
-
+          body_path: ${{ env.TAG_PATH }}/release.txt
+          files: ${{ env.FIRMWARE }}/*
 
   job_organize_tags:
-    needs: [job_init, job_source_init, job_generate_release_tag, job_build_toolchain, job_build, job_upload_release]
+    needs: [job_init, job_source_init, job_generate_release_tag, job_build_toolchain, job_build]
     if: ${{ always() }}
     runs-on: ubuntu-24.04
     name: Organize-Release-Tags
         
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
+    - name: Checkout
+      uses: actions/checkout@v4
+      with:
+        fetch-depth: 0
 
-      - name: Pull the latest changes
-        run: |
-          git pull origin ${{ github.ref_name }}
+    - name: Pull the latest changes
+      run: |
+        git pull origin ${{ github.ref_name }}
+    - name: Download Tags
+      uses: actions/download-artifact@v4
+      with:
+        name: release_tag
 
-      - name: Download Tags
-        uses: actions/download-artifact@v4
-        with:
-          name: release_tag
+    - name: Organize Tags
+      id: organize_tags
+      # env:
+      #   GH_TOKEN: ${{ github.token }}
+      run: |
+          chmod +x $ORGANIZE_TAG_SH
+          $GITHUB_WORKSPACE/$ORGANIZE_TAG_SH "${{ github.token }}" "${{ github.repository }}" "${{ github.run_id }}"
+    - name: Upload Tags To Artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: release_tag_final
+        path: release.txt
+        retention-days: 5
 
-      - name: Organize Tags
-        id: organize_tags
-        # env:
-        #   GH_TOKEN: ${{ github.token }}
-        run: |
-            chmod +x $ORGANIZE_TAG_SH
-            $GITHUB_WORKSPACE/$ORGANIZE_TAG_SH "${{ github.token }}" "${{ github.repository }}" "${{ github.run_id }}"
+    - name: Upload Release Tag
+      uses: softprops/action-gh-release@v2.0.8
+      if: steps.organize_tags.outputs.status == 'success'
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        tag_name: ${{ needs.job_init.outputs.output_release_tag }}
+        body_path: release.txt
 
-      - name: Upload Tags To Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: release_tag_final_attempt_${{ fromJSON(github.run_attempt) }}
-          path: release.txt
-          retention-days: 5
-
-      - name: Upload Release Tag
-        uses: softprops/action-gh-release@v2.0.8
-        if: steps.organize_tags.outputs.status == 'success'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ needs.job_init.outputs.output_release_tag }}
-          body_path: release.txt
-
-      - name: Trigger build
-        if: steps.organize_tags.outputs.status == 'success' && fromJSON(github.run_attempt) < 2
-        uses: peter-evans/repository-dispatch@v3
-        with:
-          token: ${{ secrets.MY_SECRET_PAT }}
-          repository: smallprogram/MyAction
-          event-type: openwrt_compilation_completed    
-
-  rerun-failed-jobs:
-    runs-on: ubuntu-24.04
-    needs: [job_init, job_source_init, job_generate_release_tag, job_build_toolchain, job_build, job_upload_release, job_organize_tags]
-    if: failure() && fromJSON(github.run_attempt) < 3
-    steps:
-      - name: Rerun failed jobs in the current workflow
-        env:
-          GH_REPO: ${{ github.repository }}
-          GH_TOKEN: ${{ github.token }}
-        run: |
-          echo "Retry failed jobs for the ${{ fromJSON(github.run_attempt) }} time, Retry 3 times in total"
-          gh workflow run Retry_Failure_Jobs.yml -F run_id=${{ github.run_id }}
-      
+    - name: Trigger build
+      if: steps.organize_tags.outputs.status == 'success'
+      uses: peter-evans/repository-dispatch@v3
+      with:
+        token: ${{ secrets.MY_SECRET_PAT }}
+        repository: smallprogram/MyAction
+        event-type: openwrt_compilation_completed
