udpate workflow add error result

diff --git a/.github/workflows/Build-OpenWrt_Multi-Platform(V2).yml b/.github/workflows/Build-OpenWrt_Multi-Platform(V2).yml
--- a/.github/workflows/Build-OpenWrt_Multi-Platform(V2).yml
+++ b/.github/workflows/Build-OpenWrt_Multi-Platform(V2).yml
@@ -126,7 +126,7 @@ jobs:
       - name: Maximize Build Space
         uses: easimon/maximize-build-space@master
         with:
-          root-reserve-mb: 3072
+          root-reserve-mb: 2560
           swap-size-mb: 1024
           remove-dotnet: 'true'
           remove-android: 'true'
@@ -372,7 +372,7 @@ jobs:
     - name: Maximize Build Space
       uses: easimon/maximize-build-space@master
       with:
-        root-reserve-mb: 3072
+        root-reserve-mb: 2560
         swap-size-mb: 1024
         remove-dotnet: 'true'
         remove-android: 'true'
@@ -637,24 +637,37 @@ jobs:
       run: |
         cd openwrt
         rm -rf compile_log/*
+        is_complie_error=0
         if [[ "${{ github.event.inputs.is_display_detailed }}" == "true" ]]; then
           if [[ "${{ github.event.inputs.is_single_threaded }}" == "true" ]]; then
               echo "1 threads compile frimware"
               make -j1 V=s | tee -a compile_log/log_${{ matrix.platforms }}_6_generate_frimware.log
+              is_complie_error=${PIPESTATUS[0]}
           else
               echo "$(nproc) threads compile frimware"
               make -j$(nproc) V=s | tee -a compile_log/log_${{ matrix.platforms }}_6_generate_frimware.log
+              is_complie_error=${PIPESTATUS[0]}
           fi
         else
           if [[ "${{ github.event.inputs.is_single_threaded }}" == "true" ]]; then
               echo "1 threads compile frimware"
               make -j1 | tee -a compile_log/log_${{ matrix.platforms }}_6_generate_frimware.log
+              is_complie_error=${PIPESTATUS[0]}
           else
               echo "$(nproc) threads compile frimware"
               make -j$(nproc) | tee -a compile_log/log_${{ matrix.platforms }}_6_generate_frimware.log
+              is_complie_error=${PIPESTATUS[0]}
           fi
         fi
-        echo "status=success" >> $GITHUB_OUTPUT
+
+        echo "complie result： $is_complie_error"
+        if [ "$is_complie_error" -eq 0 ]; then
+          echo "status=success" >> $GITHUB_OUTPUT
+        else
+          echo "status=failure" >> $GITHUB_OUTPUT
+        fi
+
+
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
         echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
